### ISSUE TITLE
Panic on annotations

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#150]
```
019/11/18 11:05:53 Fatal error: interface conversion: interface {} is nil, not map[string]interface {} - goroutine 1 [running]:
runtime/debug.Stack(0xc0001ac918, 0x1345b20, 0xc000397aa0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
main.main.func1()
        /Users/michaelsauter/dev/opendevstack/tailor/cmd/tailor/main.go:233 +0x57
panic(0x1345b20, 0xc000397aa0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/opendevstack/tailor/pkg/openshift.(*ResourceItem).parseConfig(0xc0002f8e10, 0xc000396f00, 0x1, 0x0)
        /Users/michaelsauter/dev/opendevstack/tailor/pkg/openshift/item.go:181
```

**Comment by michaelsauter** [comment]
This happened because `annotations` where on the wrong level (not nested within `metadata`). But it should be handled gracefully.

**Comment by michaelsauter** [comment]
Cannot reproduce.
